export type Trip = {
  id: number
  title: string
  type: string
  difficulty: string
  duration: string
  price: number
  location: string
  coordinates: [number, number]
  image: string
  description: string
  rating: number
  maxParticipants: string
  availableDates: string[]
  publishDate: string
  bookingDeadline: string
  // Modalidades disponibles en el viaje
  modalities?: ("buceo" | "certificacion" | "dsd" | "acompanante")[]
  // Detalle extendido
  heroImage?: string
  galleryImages?: string[]
  itinerary?: { day: string; title: string; activities: string[] }[]
  includes?: string[]
  excludes?: string[]
  highlights?: string[]
  meetingPoint?: string
  whatsappNumber?: string
}

export const trips: Trip[] = [
  {
    id: 1,
    title: "Certificación / Buceo en Veracruz",
    type: "trip",
    difficulty: "all",
    duration: "Quinta Semana (Ago)",
    price: 9500,
    location: "Veracruz",
    coordinates: [-96.1429, 19.1738],
    image: "/Wreck.webp",
    heroImage: "/Wreck.webp",
    galleryImages: ["/Wreck.webp", "/Buzos%20de%20abismo.webp", "/cabo%20Pulmo.webp"],
    modalities: ["buceo", "certificacion", "dsd", "acompanante"],
    description: "El Parque Nacional Sistema Arrecifal Veracruzano es una de las joyas ocultas del buceo en México. Desde la imponente pared de coral de La Blanquilla hasta los místicos barcos hundidos como el Comodoro Manuel Azueta, Veracruz ofrece una aventura subacuática única, llena de historia, pasadizos de coral y una vida marina sorprendente.",
    rating: 5.0,
    maxParticipants: "Variable",
    availableDates: ["2026-08-28", "2026-08-29", "2026-08-30"],
    publishDate: "2026-06-28",
    bookingDeadline: "2026-07-28",
    highlights: [
      "Parque Nacional Sistema Arrecifal Veracruzano",
      "Barcos hundidos históricos: el Comodoro Manuel Azueta",
      "Pared de coral de La Blanquilla y pasadizos de coral",
      "Fotografía subacuática profesional incluida",
      "Logística todo incluido en destino — sin cargos ocultos",
      "Hospedaje en Hotel Balajú sobre el Boulevard",
    ],
    itinerary: [
      {
        day: "Día 1 — Viernes",
        title: "Llegada y primera inmersión",
        activities: [
          "Llegada al punto de encuentro en Veracruz",
          "Charla de bienvenida y briefing de seguridad",
          "Primera inmersión de reconocimiento (tarde)",
          "Cena de grupo",
        ],
      },
      {
        day: "Día 2 — Sábado",
        title: "Día completo de buceo",
        activities: [
          "Inmersión matutina en el Arrecife Sacrificios",
          "Almuerzo a bordo",
          "Inmersión vespertina en naufragio histórico",
          "Sesión de fotos y debriefing",
        ],
      },
      {
        day: "Día 3 — Domingo",
        title: "Cierre y regreso",
        activities: [
          "Inmersión final en la mañana",
          "Desayuno y ceremonia de certificación",
          "Regreso a casa",
        ],
      },
    ],
    includes: [
      "Instructor de buceo certificado acompañando al grupo desde la CDMX",
      "Guías locales expertos certificados por el parque nacional",
      "4 buceos espectaculares (arrecifes / barcos hundidos según condiciones)",
      "Seguro de buceo con cobertura total durante las actividades",
      "Renta de equipo completo (BCD, regulador, traje de neopreno, máscara, aletas y plomos)",
      "Hospedaje en Hotel Balajú (habitaciones compartidas, 3 días y 2 noches)",
      "Lunch y bebidas a bordo durante los días de navegación",
      "Fotografías profesionales subacuáticas de tus inmersiones de regalo",
      "Propinas incluidas para marineros y staff del centro de buceo",
      "Kit de bienvenida: playera oficial de la expedición ABISMO",
    ],
    excludes: [
      "Transporte Ciudad de México – Veracruz – Ciudad de México",
      "Comidas y cenas en el puerto",
      "Traslados locales no especificados",
      "Gastos personales o extras en el hotel",
    ],
    meetingPoint: "Hotel Balajú, Boulevard Manuel Ávila Camacho, Veracruz",
    whatsappNumber: "5215548481746",
  },
  {
    id: 2,
    title: "Tiburón Ballena en Cancún + Cursos",
    type: "trip",
    difficulty: "all",
    duration: "Temporada Especial (Sept)",
    price: 20000,
    location: "Cancún",
    coordinates: [-86.8515, 21.1619],
    image: "/siguiente%20viaje.webp",
    heroImage: "/siguiente%20viaje.webp",
    galleryImages: ["/siguiente%20viaje.webp", "/Amanecer%20isla.webp", "/leon%20marino.webp"],
    modalities: ["buceo", "acompanante"],
    description: "Septiembre 2026 — Cierre de temporada del Tiburón Ballena. Vie 11 al Dom 13 de Septiembre. Publicidad desde el 11 de Julio. Reserva antes del 11 de Agosto.",
    rating: 5.0,
    maxParticipants: "8",
    availableDates: ["2026-09-11", "2026-09-12", "2026-09-13"],
    publishDate: "2026-07-11",
    bookingDeadline: "2026-08-11",
    highlights: [
      "Nado con el pez más grande del mundo",
      "Último fin de semana de temporada 2026",
      "Aguas cálidas del Caribe mexicano",
      "Grupos de máximo 8 personas",
    ],
    itinerary: [
      {
        day: "Día 1 — Viernes",
        title: "Llegada a Cancún",
        activities: [
          "Check-in en el hotel",
          "Briefing sobre el tiburón ballena y protocolo de snorkel",
          "Cena de grupo con el equipo",
        ],
      },
      {
        day: "Día 2 — Sábado",
        title: "Encuentro con el Tiburón Ballena",
        activities: [
          "Salida temprana en lancha hacia Isla Mujeres",
          "Snorkel con tiburones ballena (2–3 sesiones)",
          "Avistamiento de rayas manta",
          "Tarde libre en Isla Mujeres",
        ],
      },
      {
        day: "Día 3 — Domingo",
        title: "Buceo en arrecife + regreso",
        activities: [
          "2 inmersiones en el arrecife Mesoamericano",
          "Almuerzo de despedida",
          "Regreso a Cancún",
        ],
      },
    ],
    includes: [
      "2 noches de hospedaje en Cancún",
      "Tour de tiburón ballena con guía certificado",
      "2 inmersiones en arrecife",
      "Seguro de actividades acuáticas",
      "Desayunos y cenas",
      "Traslados hotel–muelle",
    ],
    excludes: [
      "Vuelos a Cancún",
      "Equipo de buceo personal",
      "Bebidas",
      "Propinas para la tripulación",
    ],
    meetingPoint: "Marina Puerto Juárez, Cancún, Q.Roo",
    whatsappNumber: "5215548481746",
  },
  {
    id: 3,
    title: "Gordo Banks y Las Ventanas",
    type: "trip",
    difficulty: "advanced",
    duration: "Temporada Especial (Nov)",
    price: 28000,
    location: "Los Cabos, BCS",
    coordinates: [-109.9167, 23.0],
    image: "/cabo%20pulmo%20ballena.webp",
    heroImage: "/cabo%20pulmo%20ballena.webp",
    galleryImages: ["/cabo%20pulmo%20ballena.webp", "/cabo%20Pulmo.webp", "/leon%20marino.webp"],
    modalities: ["buceo", "acompanante"],
    description: "Noviembre 2026 — El mejor mes para grandes pelágicos y tiburones martillo en Gordo Banks. Jue 12 al Dom 15 de Noviembre. Publicidad desde el 12 de Septiembre. Reserva antes del 12 de Octubre.",
    rating: 5.0,
    maxParticipants: "8",
    availableDates: ["2026-11-12", "2026-11-13", "2026-11-14", "2026-11-15"],
    publishDate: "2026-09-12",
    bookingDeadline: "2026-10-12",
    highlights: [
      "Tiburones martillo en temporada peak",
      "Grandes pelágicos: marlín, dorado, atún",
      "Gordo Banks, uno de los mejores sitios de buceo del mundo",
      "Solo 8 lugares disponibles",
    ],
    itinerary: [
      {
        day: "Día 1 — Jueves",
        title: "Llegada a Los Cabos",
        activities: [
          "Check-in en marina",
          "Reunión de equipo y revisión de equipos",
          "Cena en el puerto",
        ],
      },
      {
        day: "Día 2 — Viernes",
        title: "Gordo Banks – Inmersiones profundas",
        activities: [
          "Salida antes del amanecer hacia Gordo Banks",
          "2 inmersiones en la banca norte (tiburones martillo)",
          "Almuerzo a bordo",
          "Inmersión vespertina en Las Ventanas",
        ],
      },
      {
        day: "Día 3 — Sábado",
        title: "Cabo Pulmo",
        activities: [
          "Traslado a Cabo Pulmo (Patrimonio Mundial UNESCO)",
          "2 inmersiones en el arrecife de coral más antiguo del Pacífico",
          "Avistamiento de lobos marinos",
          "Noche en La Paz",
        ],
      },
      {
        day: "Día 4 — Domingo",
        title: "Regreso",
        activities: [
          "Inmersión de cierre en Los Cabos",
          "Desayuno de despedida",
          "Traslado al aeropuerto",
        ],
      },
    ],
    includes: [
      "3 noches de hospedaje",
      "7 inmersiones guiadas",
      "Combustible y tripulación",
      "Seguro de buceo especializado",
      "Desayunos y cenas",
      "Nitrox disponible (costo extra)",
    ],
    excludes: [
      "Vuelos a Los Cabos",
      "Equipo de buceo (opcional renta)",
      "Almuerzo del día 1 y 4",
      "Propinas",
    ],
    meetingPoint: "Marina Cabo San Lucas, Local 7",
    whatsappNumber: "5215548481746",
  },
  {
    id: 4,
    title: "Buceo Continuo / Cursos en Acapulco",
    type: "trip",
    difficulty: "all",
    duration: "Quinta Semana (Ene)",
    price: 9500,
    location: "Acapulco",
    coordinates: [-99.8901, 16.8531],
    image: "/buzosenAcapulco.webp",
    heroImage: "/buzosenAcapulco.webp",
    galleryImages: ["/buzosenAcapulco.webp", "/Buzos%20de%20abismo.webp", "/Wreck.webp"],
    modalities: ["buceo", "certificacion", "dsd", "acompanante"],
    description: "Déjate sorprender por la magia del Pacífico mexicano. Descubre arrecifes llenos de vida, barcos hundidos, caballitos de mar, rayas águila y una biodiversidad fascinante. Ya seas buzo certificado, quieras obtener tu certificación internacional PADI, o simplemente desees vivir tu primera experiencia bajo el agua, ¡este viaje es para ti!",
    rating: 5.0,
    maxParticipants: "12",
    availableDates: ["2027-01-29", "2027-01-30", "2027-01-31"],
    publishDate: "2026-11-29",
    bookingDeadline: "2026-12-29",
    highlights: [
      "Arrecifes llenos de vida y barcos hundidos",
      "Caballitos de mar, rayas águila y biodiversidad fascinante",
      "Fotografía subacuática profesional incluida",
      "Logística todo incluido en destino — sin cargos ocultos",
      "Instructores certificados y grupos pequeños",
      "Comunidad ABISMO: más que un viaje, una familia",
    ],
    itinerary: [
      {
        day: "Día 1 — Viernes",
        title: "Llegada y adaptación",
        activities: [
          "Llegada a Acapulco",
          "Revisión de equipo y briefing",
          "Primera inmersión de adaptación",
          "Cena de grupo",
        ],
      },
      {
        day: "Día 2 — Sábado",
        title: "Día intensivo de buceo",
        activities: [
          "3 inmersiones en puntos icónicos de Acapulco",
          "Práctica de habilidades en agua abierta",
          "Examen teórico (para quienes buscan certificación)",
          "Cena de celebración",
        ],
      },
      {
        day: "Día 3 — Domingo",
        title: "Cierre de curso",
        activities: [
          "2 inmersiones finales",
          "Entrega de certificaciones",
          "Desayuno de despedida",
        ],
      },
    ],
    includes: [
      "Instructor de buceo certificado a cargo del grupo",
      "Guía de buceo local experto en la zona",
      "4 buceos en embarcaciones cómodas y seguras",
      "Seguro de buceo de amplia cobertura",
      "Renta de equipo completo (BCD, regulador, traje de neopreno, máscara, aletas y plomos)",
      "Hospedaje en Hotel Alba Suites (habitaciones compartidas)",
      "Lunch y bebidas a bordo de la embarcación",
      "Fotografías profesionales de tus inmersiones de regalo",
      "Propinas incluidas para la tripulación y staff local",
      "Kit de bienvenida: playera oficial de la expedición ABISMO",
    ],
    excludes: [
      "Transporte Ciudad de México – Acapulco – Ciudad de México",
      "Comidas y cenas no especificadas en el itinerario",
      "Traslados locales en Acapulco",
      "Cualquier servicio o gasto no mencionado en el programa",
    ],
    meetingPoint: "Club de Yates Acapulco, Costera Miguel Alemán",
    whatsappNumber: "5215548481746",
  },
  {
    id: 5,
    title: "Mérida Cenotes y Apnea",
    type: "trip",
    difficulty: "intermediate",
    duration: "Especial Antes de Semana Santa (Mar)",
    price: 22000,
    location: "Mérida / Cenotes",
    coordinates: [-89.6237, 20.9674],
    image: "/Amanecer%20isla.webp",
    heroImage: "/Amanecer%20isla.webp",
    galleryImages: ["/Amanecer%20isla.webp", "/Buzos%20en%20belice.webp", "/cabo%20Pulmo.webp"],
    modalities: ["buceo", "acompanante"],
    description: "Marzo 2027 — Especial antes de Semana Santa. Aguas tranquilas en cenotes. Vie 12 al Lun 15 de Marzo. Publicidad desde el 12 de Enero. Reserva antes del 12 de Febrero.",
    rating: 5.0,
    maxParticipants: "8",
    availableDates: ["2027-03-12", "2027-03-13", "2027-03-14", "2027-03-15"],
    publishDate: "2027-01-12",
    bookingDeadline: "2027-02-12",
    highlights: [
      "Cenotes de cristal: Dos Ojos, Ik Kil, Xlacah",
      "Introducción a la apnea (freediving)",
      "Sistema de cuevas subacuáticas",
      "Antes del aumento de precios de Semana Santa",
    ],
    itinerary: [
      {
        day: "Día 1 — Viernes",
        title: "Llegada a Mérida",
        activities: [
          "Check-in en Mérida",
          "Recorrido por el centro histórico",
          "Clase teórica de apnea",
          "Cena yucateca",
        ],
      },
      {
        day: "Día 2 — Sábado",
        title: "Cenotes del sur",
        activities: [
          "Cenote Ik Kil (foto icónica del Yucatán)",
          "Snorkel en Cenote Azul",
          "Práctica de apnea en aguas tranquilas",
          "Hacienda colonial para descanso",
        ],
      },
      {
        day: "Día 3 — Domingo",
        title: "Sistema Dos Ojos",
        activities: [
          "Buceo en cueva en Dos Ojos (2 inmersiones)",
          "Formaciones estalactitas y estalagmitas",
          "Tarde libre en Tulum",
          "Cena en la costa",
        ],
      },
      {
        day: "Día 4 — Lunes",
        title: "Cenote final y regreso",
        activities: [
          "Visita al Cenote Xlacah (Dzibilchaltún)",
          "Sesión de apnea de cierre",
          "Regreso a Mérida / aeropuerto",
        ],
      },
    ],
    includes: [
      "3 noches de hospedaje",
      "Ingresos a todos los cenotes",
      "Guía de buceo en cueva certificado",
      "Equipo de snorkel",
      "Transporte inter-cenotes",
      "Desayunos y cenas",
    ],
    excludes: [
      "Vuelos a Mérida",
      "Equipo de buceo personal",
      "Comidas del mediodía",
      "Propinas",
    ],
    meetingPoint: "Hotel The Diplomat Boutique, Calle 78 Mérida",
    whatsappNumber: "5215548481746",
  },
  {
    id: 6,
    title: "Certificación / Buceo en Veracruz",
    type: "trip",
    difficulty: "all",
    duration: "Quinta Semana (May)",
    price: 9500,
    location: "Veracruz",
    coordinates: [-96.1429, 19.1738],
    image: "/Wreck.webp",
    heroImage: "/Wreck.webp",
    galleryImages: ["/Wreck.webp", "/Buzos%20de%20abismo.webp", "/cabo%20Pulmo.webp"],
    modalities: ["buceo", "certificacion", "dsd", "acompanante"],
    description: "El Parque Nacional Sistema Arrecifal Veracruzano es una de las joyas ocultas del buceo en México. Desde la imponente pared de coral de La Blanquilla hasta los místicos barcos hundidos como el Comodoro Manuel Azueta, Veracruz ofrece una aventura subacuática única, llena de historia, pasadizos de coral y una vida marina sorprendente.",
    rating: 5.0,
    maxParticipants: "Variable",
    availableDates: ["2027-05-28", "2027-05-29", "2027-05-30"],
    publishDate: "2027-03-28",
    bookingDeadline: "2027-04-28",
    highlights: [
      "Parque Nacional Sistema Arrecifal Veracruzano",
      "Barcos hundidos históricos: el Comodoro Manuel Azueta",
      "Pared de coral de La Blanquilla y pasadizos de coral",
      "Fotografía subacuática profesional incluida",
      "Logística todo incluido en destino — sin cargos ocultos",
      "Hospedaje en Hotel Balajú sobre el Boulevard",
    ],
    itinerary: [
      {
        day: "Día 1 — Viernes",
        title: "Llegada y primera inmersión",
        activities: [
          "Llegada al punto de encuentro en Veracruz",
          "Charla de bienvenida y briefing de seguridad",
          "Primera inmersión de reconocimiento",
          "Cena de grupo",
        ],
      },
      {
        day: "Día 2 — Sábado",
        title: "Día completo de buceo",
        activities: [
          "Inmersión matutina en Arrecife Sacrificios",
          "Almuerzo a bordo",
          "Inmersión vespertina en naufragio histórico",
          "Sesión de fotos y debriefing",
        ],
      },
      {
        day: "Día 3 — Domingo",
        title: "Cierre y certificación",
        activities: [
          "Inmersión final en la mañana",
          "Entrega de certificaciones PADI",
          "Desayuno y regreso",
        ],
      },
    ],
    includes: [
      "Instructor de buceo certificado acompañando al grupo desde la CDMX",
      "Guías locales expertos certificados por el parque nacional",
      "4 buceos espectaculares (arrecifes / barcos hundidos según condiciones)",
      "Seguro de buceo con cobertura total durante las actividades",
      "Renta de equipo completo (BCD, regulador, traje de neopreno, máscara, aletas y plomos)",
      "Hospedaje en Hotel Balajú (habitaciones compartidas, 3 días y 2 noches)",
      "Lunch y bebidas a bordo durante los días de navegación",
      "Fotografías profesionales subacuáticas de tus inmersiones de regalo",
      "Propinas incluidas para marineros y staff del centro de buceo",
      "Kit de bienvenida: playera oficial de la expedición ABISMO",
    ],
    excludes: [
      "Transporte Ciudad de México – Veracruz – Ciudad de México",
      "Comidas y cenas en el puerto",
      "Traslados locales no especificados",
      "Gastos personales o extras en el hotel",
    ],
    meetingPoint: "Hotel Balajú, Boulevard Manuel Ávila Camacho, Veracruz",
    whatsappNumber: "5215548481746",
  },
  {
    id: 7,
    title: "Certificación / Buceo en Acapulco",
    type: "trip",
    difficulty: "all",
    duration: "Quinta Semana (Jul)",
    price: 9500,
    location: "Acapulco",
    coordinates: [-99.8901, 16.8531],
    image: "/buzosenAcapulco.webp",
    heroImage: "/buzosenAcapulco.webp",
    galleryImages: ["/buzosenAcapulco.webp", "/Buzos%20de%20abismo.webp", "/Wreck.webp"],
    modalities: ["buceo", "certificacion", "dsd", "acompanante"],
    description: "Déjate sorprender por la magia del Pacífico mexicano. Descubre arrecifes llenos de vida, barcos hundidos, caballitos de mar, rayas águila y una biodiversidad fascinante. Ya seas buzo certificado, quieras obtener tu certificación internacional PADI, o simplemente desees vivir tu primera experiencia bajo el agua, ¡este viaje es para ti!",
    rating: 5.0,
    maxParticipants: "12",
    availableDates: ["2027-07-30", "2027-07-31", "2027-08-01"],
    publishDate: "2027-05-30",
    bookingDeadline: "2027-06-30",
    highlights: [
      "Arrecifes llenos de vida y barcos hundidos",
      "Caballitos de mar, rayas águila y biodiversidad fascinante",
      "Fotografía subacuática profesional incluida",
      "Logística todo incluido en destino — sin cargos ocultos",
      "Instructores certificados y grupos pequeños",
      "Comunidad ABISMO: más que un viaje, una familia",
    ],
    itinerary: [
      {
        day: "Día 1 — Viernes",
        title: "Llegada a Acapulco",
        activities: [
          "Check-in y briefing",
          "Primera inmersión de adaptación (tarde)",
          "Cena en el malecón",
        ],
      },
      {
        day: "Día 2 — Sábado",
        title: "Certificación intensiva",
        activities: [
          "3 inmersiones con entrenamiento de habilidades",
          "Examen teórico PADI",
          "Práctica nocturna opcional",
        ],
      },
      {
        day: "Día 3 — Domingo",
        title: "Expedición final",
        activities: [
          "2 inmersiones de exploración",
          "Entrega de certificados",
          "Regreso a casa",
        ],
      },
    ],
    includes: [
      "Instructor de buceo certificado a cargo del grupo",
      "Guía de buceo local experto en la zona",
      "4 buceos en embarcaciones cómodas y seguras",
      "Seguro de buceo de amplia cobertura",
      "Renta de equipo completo (BCD, regulador, traje de neopreno, máscara, aletas y plomos)",
      "Hospedaje en Hotel Alba Suites (habitaciones compartidas)",
      "Lunch y bebidas a bordo de la embarcación",
      "Fotografías profesionales de tus inmersiones de regalo",
      "Propinas incluidas para la tripulación y staff local",
      "Kit de bienvenida: playera oficial de la expedición ABISMO",
    ],
    excludes: [
      "Transporte Ciudad de México – Acapulco – Ciudad de México",
      "Comidas y cenas no especificadas en el itinerario",
      "Traslados locales en Acapulco",
      "Cualquier servicio o gasto no mencionado en el programa",
    ],
    meetingPoint: "Club de Yates Acapulco, Costera Miguel Alemán",
    whatsappNumber: "5215548481746",
  },
  {
    id: 8,
    title: "Certificación / Buceo en Veracruz",
    type: "trip",
    difficulty: "all",
    duration: "Quinta Semana (Ago)",
    price: 9500,
    location: "Veracruz",
    coordinates: [-96.1429, 19.1738],
    image: "/Wreck.webp",
    heroImage: "/Wreck.webp",
    galleryImages: ["/Wreck.webp", "/Buzos%20de%20abismo.webp", "/cabo%20Pulmo.webp"],
    modalities: ["buceo", "certificacion", "dsd", "acompanante"],
    description: "El Parque Nacional Sistema Arrecifal Veracruzano es una de las joyas ocultas del buceo en México. Desde la imponente pared de coral de La Blanquilla hasta los místicos barcos hundidos como el Comodoro Manuel Azueta, Veracruz ofrece una aventura subacuática única, llena de historia, pasadizos de coral y una vida marina sorprendente.",
    rating: 5.0,
    maxParticipants: "Variable",
    availableDates: ["2027-08-27", "2027-08-28", "2027-08-29"],
    publishDate: "2027-06-27",
    bookingDeadline: "2027-07-27",
    highlights: [
      "Parque Nacional Sistema Arrecifal Veracruzano",
      "Barcos hundidos históricos: el Comodoro Manuel Azueta",
      "Pared de coral de La Blanquilla y pasadizos de coral",
      "Fotografía subacuática profesional incluida",
      "Logística todo incluido en destino — sin cargos ocultos",
      "Hospedaje en Hotel Balajú sobre el Boulevard",
    ],
    itinerary: [
      {
        day: "Día 1 — Viernes",
        title: "Llegada y primera inmersión",
        activities: [
          "Llegada al punto de encuentro en Veracruz",
          "Charla de bienvenida y briefing de seguridad",
          "Primera inmersión de reconocimiento",
          "Cena de grupo",
        ],
      },
      {
        day: "Día 2 — Sábado",
        title: "Naufragios y arrecife",
        activities: [
          "Inmersión matutina en naufragio histórico",
          "Almuerzo a bordo",
          "Inmersión vespertina en arrecife de coral",
          "Debriefing y cena",
        ],
      },
      {
        day: "Día 3 — Domingo",
        title: "Cierre y certificación",
        activities: [
          "Inmersión de cierre",
          "Entrega de certificaciones PADI",
          "Desayuno y regreso",
        ],
      },
    ],
    includes: [
      "Instructor de buceo certificado acompañando al grupo desde la CDMX",
      "Guías locales expertos certificados por el parque nacional",
      "4 buceos espectaculares (arrecifes / barcos hundidos según condiciones)",
      "Seguro de buceo con cobertura total durante las actividades",
      "Renta de equipo completo (BCD, regulador, traje de neopreno, máscara, aletas y plomos)",
      "Hospedaje en Hotel Balajú (habitaciones compartidas, 3 días y 2 noches)",
      "Lunch y bebidas a bordo durante los días de navegación",
      "Fotografías profesionales subacuáticas de tus inmersiones de regalo",
      "Propinas incluidas para marineros y staff del centro de buceo",
      "Kit de bienvenida: playera oficial de la expedición ABISMO",
    ],
    excludes: [
      "Transporte Ciudad de México – Veracruz – Ciudad de México",
      "Comidas y cenas en el puerto",
      "Traslados locales no especificados",
      "Gastos personales o extras en el hotel",
    ],
    meetingPoint: "Hotel Balajú, Boulevard Manuel Ávila Camacho, Veracruz",
    whatsappNumber: "5215548481746",
  },
  {
    id: 9,
    title: "Buceo Profundo / Continuo en Acapulco",
    type: "trip",
    difficulty: "advanced",
    duration: "Quinta Semana (Oct)",
    price: 9500,
    location: "Acapulco",
    coordinates: [-99.8901, 16.8531],
    image: "/Buzos%20de%20abismo.webp",
    heroImage: "/Buzos%20de%20abismo.webp",
    galleryImages: ["/Buzos%20de%20abismo.webp", "/buzosenAcapulco.webp", "/cabo%20pulmo%20ballena.webp"],
    modalities: ["buceo", "certificacion", "dsd", "acompanante"],
    description: "Déjate sorprender por la magia del Pacífico mexicano. Descubre arrecifes llenos de vida, barcos hundidos, caballitos de mar, rayas águila y una biodiversidad fascinante. Ya seas buzo certificado, quieras obtener tu certificación internacional PADI, o simplemente desees vivir tu primera experiencia bajo el agua, ¡este viaje es para ti!",
    rating: 5.0,
    maxParticipants: "8",
    availableDates: ["2027-10-29", "2027-10-30", "2027-10-31"],
    publishDate: "2027-08-29",
    bookingDeadline: "2027-09-29",
    highlights: [
      "Arrecifes llenos de vida y barcos hundidos",
      "Caballitos de mar, rayas águila y biodiversidad fascinante",
      "Fotografía subacuática profesional incluida",
      "Logística todo incluido en destino — sin cargos ocultos",
      "Instructores certificados y grupos pequeños",
      "Comunidad ABISMO: más que un viaje, una familia",
    ],
    itinerary: [
      {
        day: "Día 1 — Viernes",
        title: "Llegada y briefing técnico",
        activities: [
          "Check-in y revisión de equipo técnico",
          "Briefing de buceo profundo y protocolos de seguridad",
          "Inmersión de verificación (20m)",
          "Cena de equipo",
        ],
      },
      {
        day: "Día 2 — Sábado",
        title: "Buceo profundo",
        activities: [
          "Inmersión a 30–40 metros en pared submarina",
          "Avistamiento de fauna pelágica",
          "Inmersión vespertina en cueva submarina",
          "Revisión y debriefing técnico",
        ],
      },
      {
        day: "Día 3 — Domingo",
        title: "Expedición de cierre",
        activities: [
          "Inmersión profunda de cierre",
          "Registro de bitácora",
          "Desayuno de despedida y regreso",
        ],
      },
    ],
    includes: [
      "Instructor de buceo certificado a cargo del grupo",
      "Guía de buceo local experto en la zona",
      "4 buceos en embarcaciones cómodas y seguras",
      "Seguro de buceo de amplia cobertura",
      "Renta de equipo completo (BCD, regulador, traje de neopreno, máscara, aletas y plomos)",
      "Hospedaje en Hotel Alba Suites (habitaciones compartidas)",
      "Lunch y bebidas a bordo de la embarcación",
      "Fotografías profesionales de tus inmersiones de regalo",
      "Propinas incluidas para la tripulación y staff local",
      "Kit de bienvenida: playera oficial de la expedición ABISMO",
    ],
    excludes: [
      "Transporte Ciudad de México – Acapulco – Ciudad de México",
      "Comidas y cenas no especificadas en el itinerario",
      "Traslados locales en Acapulco",
      "Cualquier servicio o gasto no mencionado en el programa",
    ],
    meetingPoint: "Club de Yates Acapulco, Costera Miguel Alemán",
    whatsappNumber: "5215548481746",
  },
  {
    id: 10,
    title: "Buceo Continuo / Cursos en Acapulco",
    type: "trip",
    difficulty: "all",
    duration: "Quinta Semana (Nov)",
    price: 9500,
    location: "Acapulco",
    coordinates: [-99.8901, 16.8531],
    image: "/buzosenAcapulco.webp",
    heroImage: "/buzosenAcapulco.webp",
    galleryImages: ["/buzosenAcapulco.webp", "/Buzos%20de%20abismo.webp", "/Wreck.webp"],
    modalities: ["buceo", "certificacion", "dsd", "acompanante"],
    description: "Déjate sorprender por la magia del Pacífico mexicano. Descubre arrecifes llenos de vida, barcos hundidos, caballitos de mar, rayas águila y una biodiversidad fascinante. Ya seas buzo certificado, quieras obtener tu certificación internacional PADI, o simplemente desees vivir tu primera experiencia bajo el agua, ¡este viaje es para ti!",
    rating: 5.0,
    maxParticipants: "12",
    availableDates: ["2027-11-24", "2027-11-25", "2027-11-26", "2027-11-27", "2027-11-28"],
    publishDate: "2027-09-24",
    bookingDeadline: "2027-10-24",
    highlights: [
      "Arrecifes llenos de vida y barcos hundidos",
      "Caballitos de mar, rayas águila y biodiversidad fascinante",
      "Fotografía subacuática profesional incluida",
      "Logística todo incluido en destino — sin cargos ocultos",
      "Instructores certificados y grupos pequeños",
      "Comunidad ABISMO: más que un viaje, una familia",
    ],
    itinerary: [
      {
        day: "Día 1 — Jueves",
        title: "Llegada a Acapulco",
        activities: [
          "Check-in y briefing",
          "Primera inmersión de adaptación (tarde)",
          "Cena en el malecón",
        ],
      },
      {
        day: "Día 2 — Viernes",
        title: "Día intensivo de buceo",
        activities: [
          "3 inmersiones en puntos icónicos de Acapulco",
          "Práctica de habilidades en agua abierta",
          "Examen teórico (para quienes buscan certificación)",
          "Cena de celebración",
        ],
      },
      {
        day: "Día 3 — Sábado",
        title: "Exploración y certificación",
        activities: [
          "2 inmersiones de exploración",
          "Entrega de certificados",
          "Tarde libre en Acapulco",
        ],
      },
      {
        day: "Día 4 — Domingo",
        title: "Cierre y regreso",
        activities: [
          "Inmersión final",
          "Desayuno de despedida",
          "Regreso a casa",
        ],
      },
    ],
    includes: [
      "Instructor de buceo certificado a cargo del grupo",
      "Guía de buceo local experto en la zona",
      "4 buceos en embarcaciones cómodas y seguras",
      "Seguro de buceo de amplia cobertura",
      "Renta de equipo completo (BCD, regulador, traje de neopreno, máscara, aletas y plomos)",
      "Hospedaje en Hotel Alba Suites (habitaciones compartidas)",
      "Lunch y bebidas a bordo de la embarcación",
      "Fotografías profesionales de tus inmersiones de regalo",
      "Propinas incluidas para la tripulación y staff local",
      "Kit de bienvenida: playera oficial de la expedición ABISMO",
    ],
    excludes: [
      "Transporte Ciudad de México – Acapulco – Ciudad de México",
      "Comidas y cenas no especificadas en el itinerario",
      "Traslados locales en Acapulco",
      "Cualquier servicio o gasto no mencionado en el programa",
    ],
    meetingPoint: "Club de Yates Acapulco, Costera Miguel Alemán",
    whatsappNumber: "5215548481746",
  },
]
